# Copyright DarkBlade12 - All rights reserved.
# DarkBlade12 is the developer and respective owner of this plugin.

# This section contains general plugin settings
General_Settings:

 # Determines whether the debug mode is enabled (prints error stacktraces in the console)
 # You should only set this to 'true' if you have some problems you can't solve
 Debug_Mode_Enabled: true
 # This is the ending of the language file name that will be loaded
 # ItemSlotMachine will attempt to load 'lang_<name>.txt'
 # Built-in names are 'EN' for English and 'DE' for German
 Language_Name: EN

# This section contains general slot machine settings
SlotMachines:
 ironSlot:
  Default_Name: ironSlot<num>
  Limited_Usage:
   Enabled: true
   Amount: 5
  Coin:
   # Item format: <item_id/item_name> OR <item_id/item_name>-<data>
   Name: "&7Iron Coin"
   Lore: A coin for the Iron Slot Machines!
   Item: 2264
   Price: 50

 goldSlot:
  Default_Name: goldSlot<num>
  Limited_Usage:
   Enabled: true
   Amount: 1
  Coin:
   # Item format: <item_id/item_name> OR <item_id/item_name>-<data>
   Name: "&6Gold Coin"
   Lore: A coin for the Gold Slot Machines!
   Item: 2256
   Price: 100

 diamondSlot:
  Default_Name: diamondSlot<num>
  Limited_Usage:
   Enabled: true
   Amount: 1
  Coin:
   # Item format: <item_id/item_name> OR <item_id/item_name>-<data>
   Name: "&bDiamond Coin"
   Lore: A coin for the Diamond Slot Machines!
   Item: 2267
   Price: 200

# This section contains general design settings
Design_Settings:

 # This is the default name for designs that will be used for generating ids
 # This string has to contain <num> otherwise it'll automatically add this to the end of this name
 # Please note: <num> can't be in the middle of the name
 Default_Name: design<num>